"""create interventions

Revision ID: 6579024a9473
Revises:
Create Date: 2026-09-30 10:46:50.961755

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6579024a9473"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interventions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learner_code", sa.String(length=50), nullable=False),
        sa.Column("game_element", sa.String(length=50), nullable=False),
        sa.Column("strategy", sa.String(length=30), nullable=False),
        sa.Column("engagement_before", sa.Float(), nullable=False),
        sa.Column("engagement_after", sa.Float(), nullable=True),
        sa.Column("quiz_score", sa.Float(), nullable=True),
        sa.Column("exposure_count", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "learner_code", "game_element", "exposure_count", name="uq_learner_element_exposure"
        ),
    )
    op.create_index(
        op.f("ix_interventions_game_element"), "interventions", ["game_element"], unique=False
    )
    op.create_index(
        op.f("ix_interventions_learner_code"), "interventions", ["learner_code"], unique=False
    )
    op.create_index(op.f("ix_interventions_strategy"), "interventions", ["strategy"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interventions_strategy"), table_name="interventions")
    op.drop_index(op.f("ix_interventions_learner_code"), table_name="interventions")
    op.drop_index(op.f("ix_interventions_game_element"), table_name="interventions")
    op.drop_table("interventions")
    # ### end Alembic commands ###
