"""create learning_sessions

Revision ID: eb1802029132
Revises:
Create Date: 2026-10-07 09:17:40.112133

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb1802029132"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_code", sa.String(length=50), nullable=False),
        sa.Column("student_code", sa.String(length=50), nullable=False),
        sa.Column("course_topic", sa.String(length=200), nullable=False),
        sa.Column("gamification_element", sa.String(length=30), nullable=False),
        sa.Column("time_on_task_min", sa.Integer(), nullable=False),
        sa.Column("tasks_completed", sa.Integer(), nullable=False),
        sa.Column("engagement_score", sa.Float(), nullable=False),
        sa.Column("reward", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_code"),
    )
    op.create_index(
        op.f("ix_learning_sessions_gamification_element"),
        "learning_sessions",
        ["gamification_element"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_sessions_student_code"),
        "learning_sessions",
        ["student_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_sessions_student_code"), table_name="learning_sessions")
    op.drop_index(op.f("ix_learning_sessions_gamification_element"), table_name="learning_sessions")
    op.drop_table("learning_sessions")
    # ### end Alembic commands ###
